FPS = 15
SCREENWIDTH  = 288.0
SCREENHEIGHT = 512.0
PIPEGAPSIZE  = 100 
BASEY        = SCREENHEIGHT * 0.79
IMAGES, SOUNDS, HITMASKS = {}, {}, {}
load_saved_pool = 0
save_current_pool = 1
current_pool = []
fitness = []
total_models = 20
next_pipe_x = -1
next_pipe_hole_y = -1
generation = 1
